# Generated by Django 4.1 on 2024-04-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("expenseId", models.AutoField(primary_key=True, serialize=False)),
                ("desc", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobileNumber", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ExpensePaidBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "expenseId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.expense",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseOwedBy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "expenseId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.expense",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="createdById",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="service.user"
            ),
        ),
    ]
