# Generated by Django 4.1 on 2024-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expenseowedby",
            unique_together={("userId", "expenseId")},
        ),
        migrations.AlterUniqueTogether(
            name="expensepaidby",
            unique_together={("userId", "expenseId")},
        ),
    ]
