"""initial

Revision ID: 77a5f35d21ef
Revises: 
Create Date: 2024-02-01 19:58:15.690961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a5f35d21ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('expenseId', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('createdById', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('expenseId')
    )
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobileNumber', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expense_owed_by',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('expenseId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expenseId'], ['expense.expenseId'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('userId', 'expenseId')
    )
    op.create_table('expense_paid_by',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('expenseId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expenseId'], ['expense.expenseId'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('userId', 'expenseId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_paid_by')
    op.drop_table('expense_owed_by')
    op.drop_table('user')
    op.drop_table('expense')
    # ### end Alembic commands ###
